---
- name: ASetup Yolo-Ecommerce Site.
  hosts: all
  become: true
  roles:
  
    - mongo_setup      # Deploys the MongoDB container
    - backend_setup    # Deploys the backend container
    - client_setup   # Deploys the frontend container