- name: Pull image from repository
  docker_image:
    name: fowino/yolo-client:v1.0.5
    source: pull

- name: Create Node.js frontend Container
  docker_container:
    name: yolo-client
    image: fowino/yolo-client:v1.0.5
    networks:
      - name: app-net
    ports:
      - "3000:3000"
    command: "npm start"
    restart_policy: unless-stopped
  become: yes