apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fowino/yolo-client:v1.1.5
          ports:
            - containerPort: 3000
          env:
            - name: HOST
              value: "0.0.0.0"
          resources:
            limits:
              cpu: "100m" 
              memory: "128Mi" 
            requests:
              cpu: "100m"
              memory: "128Mi"