---
- name: Pull image from repository
  docker_image:
    name: fowino/yolo-backend:v1.0.5
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: yolo-backend
    image: fowino/yolo-backend:v1.0.5
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes